#!/usr/bin/env bash
# Create S3 bucket + CORS for stream-catalog local/dev use.
# Prereq: AWS CLI authenticated (SSO recommended):
#   aws configure sso --profile stream-catalog-dev
#   aws sso login --profile stream-catalog-dev
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PROFILE="${AWS_PROFILE:-stream-catalog-dev}"
REGION="${AWS_REGION:-us-east-1}"
BUCKET_PREFIX="${INGEST_S3_BUCKET_PREFIX:-stream-catalog-ingest}"
S3_PREFIX="${INGEST_S3_PREFIX:-deliveries}"
ASPERA_PREFIX="${ASPERA_DROP_PREFIX:-inbound}"

export AWS_PROFILE="$PROFILE"
export AWS_DEFAULT_REGION="$REGION"

aws_cli() {
  if command -v aws >/dev/null 2>&1; then
    aws "$@"
    return
  fi
  if [[ -x "$HOME/.local/bin/aws" ]]; then
    "$HOME/.local/bin/aws" "$@"
    return
  fi
  echo "AWS CLI not found. Install: uv tool install awscli" >&2
  exit 1
}

echo "==> Checking AWS credentials (profile: $PROFILE)"
if ! aws_cli sts get-caller-identity >/dev/null 2>&1; then
  echo "Not logged in. Run:" >&2
  echo "  aws configure sso --profile $PROFILE" >&2
  echo "  aws sso login --profile $PROFILE" >&2
  exit 1
fi

ACCOUNT_ID="$(aws_cli sts get-caller-identity --query Account --output text)"
BUCKET="${INGEST_S3_BUCKET:-${BUCKET_PREFIX}-${ACCOUNT_ID}}"

echo "==> Account: $ACCOUNT_ID"
echo "==> Bucket:  $BUCKET"
echo "==> Region:  $REGION"

if aws_cli s3api head-bucket --bucket "$BUCKET" 2>/dev/null; then
  echo "Bucket already exists."
else
  echo "==> Creating bucket..."
  if [[ "$REGION" == "us-east-1" ]]; then
    aws_cli s3api create-bucket --bucket "$BUCKET"
  else
    aws_cli s3api create-bucket \
      --bucket "$BUCKET" \
      --create-bucket-configuration "LocationConstraint=$REGION"
  fi
fi

echo "==> Blocking public access (recommended)"
aws_cli s3api put-public-access-block \
  --bucket "$BUCKET" \
  --public-access-block-configuration \
  "BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"

CORS_FILE="$(mktemp)"
trap 'rm -f "$CORS_FILE"' EXIT
cat >"$CORS_FILE" <<'EOF'
{
  "CORSRules": [
    {
      "AllowedHeaders": ["*"],
      "AllowedMethods": ["GET", "PUT", "HEAD"],
      "AllowedOrigins": [
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "https://*.amplifyapp.com"
      ],
      "ExposeHeaders": ["ETag"],
      "MaxAgeSeconds": 3000
    }
  ]
}
EOF

echo "==> Applying CORS"
aws_cli s3api put-bucket-cors --bucket "$BUCKET" --cors-configuration "file://$CORS_FILE"

echo "==> Ensuring prefix folders exist"
aws_cli s3api put-object --bucket "$BUCKET" --key "${S3_PREFIX}/" --body /dev/null 2>/dev/null || \
  printf '' | aws_cli s3 cp - "s3://${BUCKET}/${S3_PREFIX}/" 2>/dev/null || true
if [[ -n "$ASPERA_PREFIX" ]]; then
  printf '' | aws_cli s3 cp - "s3://${BUCKET}/${S3_PREFIX}/${ASPERA_PREFIX}/" 2>/dev/null || true
fi

TOKEN="$(openssl rand -hex 24)"
BACKEND_ENV="$ROOT/backend/.env"
FRONTEND_ENV="$ROOT/frontend/.env.local"

write_env() {
  local file="$1"
  if [[ -f "$file" ]]; then
    echo "==> Updating $file"
    # shellcheck disable=SC1090
    source "$file" 2>/dev/null || true
    TOKEN="${INGEST_OPERATOR_TOKEN:-$TOKEN}"
  else
    echo "==> Creating $file"
  fi
}

if [[ -f "$BACKEND_ENV" ]] && grep -q '^INGEST_OPERATOR_TOKEN=' "$BACKEND_ENV"; then
  TOKEN="$(grep '^INGEST_OPERATOR_TOKEN=' "$BACKEND_ENV" | cut -d= -f2-)"
fi

cat >"$BACKEND_ENV" <<EOF
# Local development — generated by scripts/setup-aws-s3.sh
DATABASE_URL=sqlite:///../data/catalog.db
CORS_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
SEED_ON_STARTUP=true

# TMDB (optional) — https://www.themoviedb.org/settings/api
TMDB_API_KEY=your_tmdb_api_key_here

# AWS — use SSO profile (no long-lived keys on laptop)
AWS_PROFILE=${PROFILE}
AWS_REGION=${REGION}

# S3 ingest / storage
INGEST_S3_BUCKET=${BUCKET}
INGEST_S3_PREFIX=${S3_PREFIX}
ASPERA_DROP_PREFIX=${ASPERA_PREFIX}
INGEST_OPERATOR_TOKEN=${TOKEN}
EOF

cat >"$FRONTEND_ENV" <<EOF
# Local dev — Vite proxies /api to localhost:8000
# VITE_API_URL=

VITE_INGEST_OPERATOR_TOKEN=${TOKEN}
EOF

echo ""
echo "Done."
echo "  Bucket:  s3://${BUCKET}/${S3_PREFIX}/${ASPERA_PREFIX}/"
echo "  Profile: ${PROFILE}"
echo "  Backend: ${BACKEND_ENV}"
echo "  Frontend:${FRONTEND_ENV}"
echo ""
echo "Restart dev servers: ./scripts/dev.sh"
echo "Open Storage UI:     http://localhost:5173/storage"
